services:
  whisper-cpp:
    container_name: whisper-cpp
    hostname: whisper-cpp
    build:
      context: /path/to/your/context
      args:
        WHISPER_CPP_VERSION: $WHISPER_CPP_VERSION
        WHISPER_MODEL: $WHISPER_MODEL
        OPENVINO_TGZ: $OPENVINO_TGZ
        OPENVINO_DIR_NAME: $OPENVINO_DIR_NAME
        OPENVINO_URL: $OPENVINO_URL
    image: optional-image-name:option-image-tags
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8910:8910
    devices:
      - /dev/dri:/dev/dri
    environment:
      WHISPER_LANG: $WHISPER_LANG
      WHISPER_BEAM_SIZE: $WHISPER_BEAM_SIZE
      WHISPER_MODEL: $WHISPER_MODEL
      WHISPER_PROMPT: $WHISPER_PROMPT

  wyoming-api:
    container_name: wyoming-api
    hostname: wyoming-api   
    build:
      context: /path/to/your/context
    restart: unless-stopped
    depends_on:
      whisper-cpp:
        condition: service_healthy
    network_mode: bridge
    ports:
      - 7891:7891
    environment:
      WHISPER_CPP_HOSTNAME: whisper-cpp-dns-or-ip
      WHISPER_CPP_PORT: 8910
